[workspace]
resolver = "3"
members = [
    "rust/terminal-adapter",
    "rust/terminal-app",
    "rust/terminal-buffer",
    "rust/terminal-core",
    "rust/terminal-foundation",
    "rust/terminal-host",
    "rust/terminal-input",
    "rust/terminal-parser",
    "rust/terminal-parser-ffi",
    "rust/terminal-renderer",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/ChicoDotNet/terminal"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
